---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: output-examples
description: show simple exampled of outputs
inputs:
  num1:
    description: simple input of a number to be processed 1 
    required: true
  num2:
    description: simple input of a number to be processed 1 
    required: true
outputs:
  multiplied: 
    value: "${{ steps.process.outputs.multiplied }}"
    description: 'multiplied'
  subtracted: 
    value: "${{ steps.process.outputs.subtracted }}"
    description: 'subtracted'
  divided: 
    value: "${{ steps.process.outputs.divided }}"
    description: 'divided'
runs:
  using: composite
  steps:
    - id: process
      name: process the inputs
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        num1=${{ inputs.num1 }}
        num2=${{ inputs.num2 }}
        echo "$((num1 * num2))" >> $CLOUDBEES_OUTPUTS/multiplied
        echo "$((num1 - num2))" >> $CLOUDBEES_OUTPUTS/subtracted
        echo "$((num1 / num2))" >> $CLOUDBEES_OUTPUTS/divided
