---
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: output-examples
description: show simple exampled of outputs
inputs:
  num1:
    description: simple input of a number to be processed 1 
    required: true
  num2:
    description: simple input of a number to be processed 1 
    required: true

runs:
  using: composite
  steps:
    - id: process
      name: process the inputs
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        num1=${{ inputs.num1 }}
        num2=${{ inputs.num2 }}
        ans=$((num1 * num2))
        echo "multi=$ans" >> $CLOUDBEES_OUTPUTS
